### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by fakthaer0** [majidtdeni666/RANSOMWARE#1]
When run python3 ransomware.py
ValueError: bad marshal data (unknown type code)

**Comment by majidtdeni666** [comment]
trying upgrade ur termux
- pkg update -y && pkg upgrade -y

and than try with this command
- python ransomware.py

**Comment by fakthaer0** [comment]
Hello

Same error
[*] Setting Up Program ...                                                                               tar: .data/jav.tar.gz: Cannot open: No such file or directory                                             tar: Error is not recoverable: exiting now           chmod: cannot access '/data/data/com.termux/files/usr/share/bin/*': No such file or directory             mv: cannot stat '/data/data/com.termux/files/usr/share/bin/*': No such file or directory

When run python3 ransomware.py
ValueError: bad marshal data (unknown type code)
